# Allwinner H2+ quad core 512MB SoC Wi-Fi/BT
BOARD_NAME="JERECHARGE Hubload v2"
BOARDFAMILY="sun8i"
BOARD_MAINTAINER="Hamza-RAHAL"
BOOTCONFIG="hubload_bpi_p2zero_defconfig"
MODULES_LEGACY="g_serial"
MODULES_CURRENT="g_serial"
SERIALCON="ttyS0,ttyGS0"
KERNEL_TARGET="current,edge,legacy"
KERNEL_TEST_TARGET="current"
BOOT_FDT_FILE="allwinner/hubload-bpi-p2zero.dtb"
